name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Create html file
      run: |
        ls
        source .venv/bin/activate
        python civic_media_scout/html_generator.py
    - name: Git Push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'gh-pages'
        commit-message: 'Automated HTML Build'
        force-add: 'true'
        files: index.html
        name: navchandar
        email: 12165092+navchandar@users.noreply.github.com 
