name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Generate html file
      run: |
        ls
        source .venv/bin/activate
        python civic_media_scout/html_generator.py
    - name: Git Push changes
      run: |
          git config --global user.email "12165092+navchandar@users.noreply.github.com"
          git config --global user.name "navchandar"
          git checkout -b gh-pages
          git add .
          git commit -m "Automated HTML Build" index.html
          git push --force origin gh-pages
